const statesData = [
    { stateName: 'ANDHRA PRADESH', pricingSlab: 'PREMIUM ( 5% )' },
    { stateName: 'ARUNACHAL PRADESH', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'ASSAM', pricingSlab: 'PREMIUM ( 5% )' },
    { stateName: 'BIHAR', pricingSlab: 'PREMIUM ( -5% )' },
    { stateName: 'CHHATTISGARH', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'GOA', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'GUJARAT', pricingSlab: 'PREMIUM ( 5% )' },
    { stateName: 'HARYANA', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'HIMACHAL PRADESH', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'JHARKHAND', pricingSlab: 'PREMIUM ( -5% )' },
    { stateName: 'KARNATAKA', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'KERALA', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'MADHYA PRADESH', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'MAHARASHTRA', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'MANIPUR', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'MEGHALAYA', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'MIZORAM', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'NAGALAND', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'ODISHA', pricingSlab: 'PREMIUM ( -5% )' },
    { stateName: 'PUNJAB', pricingSlab: 'PREMIUM ( 5% )' },
    { stateName: 'RAJASTHAN', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'SIKKIM', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'TAMIL NADU', pricingSlab: 'PREMIUM ( 5% )' },
    { stateName: 'TELANGANA', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'TRIPURA', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'UTTAR PRADESH', pricingSlab: 'PREMIUM ( -5% )' },
    { stateName: 'UTTARAKHAND', pricingSlab: 'PREMIUM ( ROI )' },
    { stateName: 'WEST BENGAL', pricingSlab: 'PREMIUM ( -5% )' },
  ];
  
  export default statesData;